# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87d7deb25bf021e72f3cdbd65699a21568fbce08922d903e36386aa88c57f19d564c16b14b328a48d704460e5a985a05c54808d3e4151ce14e0f0af456ac224

test:
  secret_key_base: d1fcf0b70dac67bd41617044b02aa79bb383ae36245dceeb24ab971b37bc56f3e352e365f2581331ea6d61ca249b48eee9934fe76f332908589d095a1ae906b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  PLACES_API_KEY: AIzaSyC-5Q8P5B0DWBa_AsAr7bsFXFPGNnW9EvM
  GEOCODER_KEY: AIzaSyBmy7kC8_I8xio5eKQJDwNG4DUBhF_9RkE

  FOURSQUARE_APP_ID: UZLBTEKQ321WI1XJ1XJJ2ZLX1FS0NTUWSNNV2SRBAX2BZUCT
  FOURSQUARE_SECRET_KEY: 3FAWVDKAGSD2EE0AMARXKFDT0SLDLNF2HUAC33OMNYUKHYW4
